spring.application.name=analytics
spring.datasource.url=jdbc:mysql://localhost:3306/sporthub_facility?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

# Automatsko kreiranje tabela na osnovu Java klasa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always